name: 'Setup TensorRT-RTX'
description: 'Download, cache and setup TensorRT-RTX SDK for specific CUDA versions'
inputs:
  cuda-version:
    description: 'CUDA Version (e.g., 12.9, 13.1)'
    required: true
  trt-version:
    description: 'TensorRT-RTX Version'
    required: false
    default: '1.3.0.35'

runs:
  using: "composite"
  steps:
    - name: Construct Filenames
      shell: bash
      id: meta
      run: |
        FILENAME="TensorRT-RTX-${{ inputs.trt-version }}-Linux-x86_64-cuda-${{ inputs.cuda-version }}-Release-external.tar.gz"
        URL="https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/1.3/$FILENAME"
        
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        echo "url=$URL" >> $GITHUB_OUTPUT
        # 统一安装路径
        INSTALL_PATH="$(pwd)/tensorrt-rtx-sdk"
        echo "install_path=${INSTALL_PATH}" >> $GITHUB_OUTPUT

    - name: Cache TensorRT-RTX
      id: cache-trt
      uses: actions/cache@v4
      with:
        path: ${{ steps.meta.outputs.install_path }}
        # 缓存 Key
        key: trt-rtx-v2-${{ runner.os }}-${{ inputs.trt-version }}-cuda-${{ inputs.cuda-version }}

    - name: Download and Extract
      if: steps.cache-trt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cache miss. Downloading from ${{ steps.meta.outputs.url }}..."
        
        # 定义最终安装路径
        INSTALL_PATH="${{ steps.meta.outputs.install_path }}"
        
        # 1. 强制清理并重新创建最终目标目录 (确保它一定存在且为空)
        rm -rf "$INSTALL_PATH"
        mkdir -p "$INSTALL_PATH"
        
        # 2. 下载
        wget -q --no-check-certificate "${{ steps.meta.outputs.url }}" -O trt_rtx.tar.gz
        
        # 3. 直接解压到目标目录
        # --strip-components=1 的作用是：解压时自动去掉第一层目录 (即去掉 TensorRT-RTX-1.3.0.35 这一层)
        # 直接把里面的 bin, lib, include 等甩到 INSTALL_PATH 里
        echo "Extracting directly to $INSTALL_PATH ..."
        tar -xf trt_rtx.tar.gz -C "$INSTALL_PATH" --strip-components=1
        
        # 4. 验证解压结果
        if [ -f "$INSTALL_PATH/include/NvInfer.h" ]; then
          echo "✅ Successfully installed to $INSTALL_PATH"
          ls -l "$INSTALL_PATH"
        else
          echo "❌ Error: Extraction failed. NvInfer.h not found."
          # 如果失败，可能是压缩包结构变了，不是一层目录。列出内容调试。
          # 备用方案：如果不确定是否有一层目录，可以尝试去掉 --strip-components=1
          # 但根据你之前的日志 Found extracted directory: temp_extract/TensorRT-RTX-1.3.0.35
          # 说明确实有一层目录，所以 strip-components=1 是完美的解决方案。
          ls -R "$INSTALL_PATH"
          exit 1
        fi
        
        # 5. 清理压缩包
        rm -f trt_rtx.tar.gz

    - name: Export Environment Variables
      shell: bash
      run: |
        echo "TRT_RTX_HOME=${{ steps.meta.outputs.install_path }}" >> $GITHUB_ENV