name: 'Setup TensorRT-RTX'
description: 'Download, cache and setup TensorRT-RTX SDK for specific CUDA versions'
inputs:
  cuda-version:
    description: 'CUDA Version (e.g., 12.9, 13.1)'
    required: true
  trt-version:
    description: 'TensorRT-RTX Version'
    required: false
    default: '1.3.0.35'

runs:
  using: "composite"
  steps:
    - name: Construct Filenames
      shell: bash
      id: meta
      run: |
        # 构造文件名：TensorRT-RTX-1.3.0.35-Linux-x86_64-cuda-12.9-Release-external.tar.gz
        FILENAME="TensorRT-RTX-${{ inputs.trt-version }}-Linux-x86_64-cuda-${{ inputs.cuda-version }}-Release-external.tar.gz"
        # 构造 URL (基于你确认的规律)
        URL="https://developer.nvidia.com/downloads/trt/rtx_sdk/secure/1.3/$FILENAME"
        
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        echo "url=$URL" >> $GITHUB_OUTPUT
        echo "install_path=${{ github.workspace }}/tensorrt-rtx-sdk" >> $GITHUB_OUTPUT

    # 使用 GitHub 官方缓存 Action
    - name: Cache TensorRT-RTX
      id: cache-trt
      uses: actions/cache@v4
      with:
        path: ${{ steps.meta.outputs.install_path }}
        # Cache Key 包含系统、TRT版本和CUDA版本
        key: trt-rtx-v1-${{ runner.os }}-${{ inputs.trt-version }}-cuda-${{ inputs.cuda-version }}

    # 如果缓存没命中，则下载
    - name: Download and Extract
      if: steps.cache-trt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cache miss. Downloading from ${{ steps.meta.outputs.url }}..."
        
        # 使用 wget 下载，-nv (简洁模式), --content-disposition (自动处理文件名)
        # 注意：如果链接未来变动需要 Cookie，这里可能需要加 Header
        wget -nv --no-check-certificate "${{ steps.meta.outputs.url }}" -O trt_rtx.tar.gz
        
        echo "Extracting..."
        mkdir -p temp_extract
        tar -xf trt_rtx.tar.gz -C temp_extract
        
        # 移动到最终目录 (github workspace 下)
        # 查找解压后的文件夹（名字通常带有版本号），并重命名为统一名称
        FOUND_DIR=$(find temp_extract -maxdepth 1 -type d -name "TensorRT-RTX*" | head -n 1)
        mv "$FOUND_DIR" "${{ steps.meta.outputs.install_path }}"
        
        # 清理
        rm -rf temp_extract trt_rtx.tar.gz

    # 设置环境变量供后续步骤使用
    - name: Export Environment Variables
      shell: bash
      run: |
        echo "TRT_RTX_HOME=${{ steps.meta.outputs.install_path }}" >> $GITHUB_ENV
        echo "✅ TensorRT-RTX Home set to: ${{ steps.meta.outputs.install_path }}"